# Add 'test' label to any change in tests dir
test:
- tests/*

common:
- model_compression_toolkit/core/common/*

keras:
- model_compression_toolkit/core/keras/*

pytorch:
- model_compression_toolkit/core/pytorch/*

docs:
- docs/*

docsrc:
- docsrc/*
